name: Validate

on:
  workflow_dispatch:
  pull_request:
    branches:
      - 'main'

jobs:
  
  SetupBuildInfo:
    runs-on: ubuntu-latest
    outputs:
      build-name: ${{ steps.SetupBuildInfo.outputs.build-name }}
      build-id: ${{ steps.SetupBuildInfo.outputs.build-id }}
      build-version: ${{ steps.SetupBuildInfo.outputs.build-version }}
      build-timestamp: ${{ steps.SetupBuildInfo.outputs.build-timestamp }}
    steps:
      
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      
      - name: SetupBuildInfo
        id: SetupBuildInfo
        run: dotnet run --project _atom/_atom.csproj SetupBuildInfo --skip --headless
  
  PackJsonExtensions:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      
      - name: PackJsonExtensions
        id: PackJsonExtensions
        run: dotnet run --project _atom/_atom.csproj PackJsonExtensions --skip --headless
  
  TestJsonExtensions:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      
      - name: TestJsonExtensions
        id: TestJsonExtensions
        run: dotnet run --project _atom/_atom.csproj TestJsonExtensions --skip --headless
  
  BenchmarkJsonExtensions:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      
      - name: BenchmarkJsonExtensions
        id: BenchmarkJsonExtensions
        run: dotnet run --project _atom/_atom.csproj BenchmarkJsonExtensions --skip --headless
